### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by Useless-Panda** [onemanbuilds/NordVPNChecker#3]
Hi! How are you? i wanted to use this program but i keep getting this error, i tried everything i could reinstalling Visual C++ and python but it didn't help.
I am using win 7 sp1

![Untitled](https://user-images.githubusercontent.com/29812920/116763695-cf228000-aa37-11eb-924b-00b42dd22e2f.jpg)

**Comment by onemanbuilds** [comment]
install vc redist all in one package if it is still missing some dlls
download them and copy them in the system32 folder

Assassin143 ***@***.***> ezt írta (időpont: 2021. máj. 1.,
Szo, 1:46):

**Comment by Useless-Panda** [comment]
VC AIO package  did not fix the issue, Manually putting .dll file in system32 got rid of the error but now cmd opens for a second the closes

**Comment by Useless-Panda** [comment]
Working fine on win 10
